apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: frontend-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: ReplicaSet
    name: frontend-app
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
