apiVersion: v1
kind: Service
metadata:
  name: react-service
  labels:
    app: react
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30000
  selector:
    app: react